spring.application.name=sahi-backend

spring.datasource.url=jdbc:mysql://localhost:3306/sahi_db
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
razorpay.key.id=rzp_test_SmYoMEnDnXTQXV
razorpay.key.secret=fUNk7o8uSXqoZ4c2YFwiZ22X
spring.main.allow-bean-definition-overriding=true